### ISSUE TITLE
binary repositories

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVIL_Admin#7]
I am not having any luck finding details on the kubernetes approach to binary repo construction.

I think the github.io pages need a redesign.  Maybe a pkgdown site would work better -- what we have
is too linear.  I will try to draft something.

**Comment by vjcitn** [comment]
Should we have a process of copying all CRAN source tarballs to a google bucket to reduce the
download time involved in building a repo?  A CRAN mirror in AnVIL?

**Comment by mtmorgan** [comment]
I was expecting `BiocManager::repositories()` to return the RStudio package manager, inherited from the base container, but instead it returns a plain-old CRAN repository. Try setting the repository to the RStudio Package Manager URL
```
> options(repos=c(CRAN="https://packagemanager.rstudio.com/all/__linux__/focal/latest"))
> BiocManager::repositories()
                                                       BioCsoft 
                  "https://bioconductor.org/packages/3.12/bioc" 
                                                        BioCann 
       "https://bioconductor.org/packages/3.12/data/annotation" 
                                                        BioCexp 
       "https://bioconductor.org/packages/3.12/data/experiment" 
                                                  BioCworkflows 
             "https://bioconductor.org/packages/3.12/workflows" 
                                                           CRAN 
"https://packagemanager.rstudio.com/all/__linux__/focal/latest" 
```
to get fast binary package installation.

The binary packages are built with https://github.com/Bioconductor/BiocKubeInstall ; Nitesh maintains this but is out for several weeks.

I was expecting `AnVIL::repositories()` to return as the first element a path to binary Bioconductor repositories, and hence `AnVIL::install()` to install binary Bioconductor packages
```
> db = available.packages(repos=AnVIL::repositories()[1])
> nrow(db)
[1] 2680
> head(rownames(db))
[1] "a4"          "a4Base"      "a4Classif"   "a4Core"      "a4Preproc"   "a4Reporting"
```
so it looks like we get fast Bioconductor binary installation for any package that has not been rebuilt since the last binary package update.

Are you sure that the problem with github pages is the presentation, or is that it has not been maintained regularly? The last commit was on August 5.

**Comment by vjcitn** [comment]
Thank you -- point taken on site maintenance.  But it seems there are too many hops from code to anvil to site content.  Let's see if I can come up with something more organic.  It is not clear that I can.
